languageCode = "en-us"
title = "Sketchnote"
baseurl = "https://slq.github.io/"

paginate = 5
DisqusShortname = "sketchnote-1"
Copyright = "All rights reserved - 2017"
canonifyurls = true

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/"
  weight = -120

[[menu.main]]
  name = "Keybase (secure msg)"
  url = "https://Keybase.io/vjeantet"
  weight = 109

[params]
  description = "this is my description"
  cover = "images/cover_polenord.jpg"
  author = "Slawek PLAMOWSKI"
  authorlocation = "Wroclaw, Poland"
  authorwebsite = "http://vjeantet.fr"
  bio= "IT Software Engineer, Java & Scala & Go enthusiast."
  logo = "images/hugo-icon.png"
  googleAnalyticsUserID = "UA-79101-12"
  
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  
  githubName = "slq"
  # gitlabName =  
  # telegramName = 
  twitterName = "slawek_pl"
  # facebookName = ""
  linkedinName = "sławomir-plamowski-5ab02728"
  
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  
  [params.social]
    twitter = "slawek_pl"

  [permalinks]
    post = "/:slug/"

  [sitemap]
    ChangeFreq = ""
    Filename = "sitemap.xml"
    Priority = "-1"