baseurl = "https://slq.github.io/"
title = "Sketchnote"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "My Name"
googleAnalytics = "XXX"
disqusShortname = "sketchnote-1"

[Author]
    name = "Slawek Plamowski"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Slawek Plamowski"
    description = "IT Software Engineer, Java & Scala & Go enthusiast."
    github = "https://github.com/slq"
    gitlab = "https://gitlab.com/slq"
    linkedin = "https://linkedin.com/in/sławomir-plamowski-5ab02728/"
    gplus = "https://google.com/slawek.plamowski"
    twitter = "https://twitter.com/slawek_pl"
    stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    email = "slawek.plamowski@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4